<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3JH0LC3" failures="0" tests="3" name="com.comcast.crm.producttest.CreateProductTest2" time="47.690" errors="1" timestamp="17 Sep 2024 17:55:31 GMT" skipped="0">
  <testcase classname="com.comcast.crm.producttest.CreateProductTest2" name="confifAS" time="5.829">
    <error message="Cannot invoke &quot;java.sql.Connection.close()&quot; because &quot;this.connect&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "this.connect" is null
at com.comcast.crm.generic.databaseutility.DatabaseUtility.closedbConnection(DatabaseUtility.java:27)
at com.comcast.crm.generic.baseUtility.BaseClass.confifAS(BaseClass.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- confifAS -->
  <testcase classname="com.comcast.crm.producttest.CreateProductTest2" name="createNewProductTest" time="16.852"/>
  <testcase classname="com.comcast.crm.producttest.CreateProductTest2" name="createProductWithVendor" time="25.009"/>
</testsuite> <!-- com.comcast.crm.producttest.CreateProductTest2 -->
